"""tests/test_grid.py
Test suite for the 500 m Bengaluru city grid generated by pipeline/01_grid.py.
Verifies spec compliance, spatial bounds, topological properties, CRS stability, and determinism.
"""

import os
import subprocess
import pandas as pd
import numpy as np
import pytest
from pyproj import Transformer

CELLS_CSV = "data/interim/cells_grid.csv"
RAIN_PIXELS_CSV = "data/interim/rain_pixels.csv"

@pytest.fixture(scope="module")
def cells_df():
    assert os.path.exists(CELLS_CSV), f"Missing {CELLS_CSV}. Run pipeline/01_grid.py first."
    return pd.read_csv(CELLS_CSV)

@pytest.fixture(scope="module")
def rain_pixels_df():
    assert os.path.exists(RAIN_PIXELS_CSV), f"Missing {RAIN_PIXELS_CSV}."
    return pd.read_csv(RAIN_PIXELS_CSV)

def test_cell_count_within_expected_range(cells_df):
    """Grid cell count must land within the 2,500 to 3,300 range (spec target ~2,900)."""
    n_cells = len(cells_df)
    assert 2500 <= n_cells <= 3300, f"Cell count {n_cells} is outside allowable range [2500, 3300]"

def test_unique_integer_cell_id(cells_df):
    """cell_id must be unique, non-null, integer from 0 to N-1."""
    assert "cell_id" in cells_df.columns, "Missing cell_id column"
    assert cells_df["cell_id"].notna().all(), "cell_id has NaN values"
    assert pd.api.types.is_integer_dtype(cells_df["cell_id"]), "cell_id is not integer type"
    assert cells_df["cell_id"].nunique() == len(cells_df), "cell_id is not unique"
    assert set(cells_df["cell_id"]) == set(range(len(cells_df))), "cell_id is not contiguous 0 to N-1"

def test_no_null_critical_fields(cells_df):
    """No NaN values allowed in lat, lon, ward, rain_pixel_id, area_km2, x_utm, y_utm, lattice_center_x, lattice_center_y."""
    critical_cols = [
        "lat", "lon", "ward", "rain_pixel_id", "area_km2",
        "x_utm", "y_utm", "lattice_center_x", "lattice_center_y"
    ]
    for col in critical_cols:
        assert col in cells_df.columns, f"Missing column {col}"
        assert cells_df[col].notna().all(), f"Found NaN values in {col}"

def test_centroid_definitions_consistency(cells_df):
    """For unclipped full cells (area_km2 >= 0.2499), x_utm and y_utm must exactly match lattice_center."""
    full_cells = cells_df[cells_df["area_km2"] >= 0.2499]
    assert np.allclose(full_cells["x_utm"], full_cells["lattice_center_x"], atol=0.02)
    assert np.allclose(full_cells["y_utm"], full_cells["lattice_center_y"], atol=0.02)

def test_wgs84_coordinate_bounds(cells_df):
    """Centroid coordinates must fall strictly within the Bengaluru bounding box (lat 12.7-13.3, lon 77.3-77.9)."""
    assert (cells_df["lat"] >= 12.7).all() and (cells_df["lat"] <= 13.3).all(), (
        f"Latitude out of bounds [12.7, 13.3]: min={cells_df['lat'].min()}, max={cells_df['lat'].max()}"
    )
    assert (cells_df["lon"] >= 77.3).all() and (cells_df["lon"] <= 77.9).all(), (
        f"Longitude out of bounds [77.3, 77.9]: min={cells_df['lon'].min()}, max={cells_df['lon'].max()}"
    )

def test_cell_area_properties(cells_df):
    """Cell area must be > 0 and <= 0.25 km^2 (500m x 500m) with tiny tolerance for floating point."""
    assert (cells_df["area_km2"] > 0).all(), "Found non-positive area_km2"
    assert (cells_df["area_km2"] <= 0.250001).all(), (
        f"Found cell with area > 0.25 km²: max={cells_df['area_km2'].max()}"
    )
    total_area = cells_df["area_km2"].sum()
    assert 700.0 <= total_area <= 720.0, f"Total area {total_area:.2f} km² deviates from ~711.59 km²"

def test_ward_identifiers(cells_df):
    """Ward identifiers must be valid integers between 1 and 198."""
    assert pd.api.types.is_integer_dtype(cells_df["ward"]), "ward is not integer type"
    assert cells_df["ward"].min() >= 1, f"Found ward < 1: {cells_df['ward'].min()}"
    assert cells_df["ward"].max() <= 198, f"Found ward > 198: {cells_df['ward'].max()}"
    assert cells_df["ward"].nunique() == 198, (
        f"Expected all 198 wards to have cells, found {cells_df['ward'].nunique()}"
    )

def test_rain_pixel_linkage(cells_df, rain_pixels_df):
    """Every cell must map to a valid rain_pixel_id present in rain_pixels.csv."""
    assert pd.api.types.is_integer_dtype(cells_df["rain_pixel_id"])
    assert set(cells_df["rain_pixel_id"]).issubset(set(rain_pixels_df["rain_pixel_id"]))
    counts_from_cells = cells_df.groupby("rain_pixel_id").size().to_dict()
    for _, row in rain_pixels_df.iterrows():
        pid = int(row["rain_pixel_id"])
        expected_count = counts_from_cells.get(pid, 0)
        assert row["n_cells"] == expected_count, (
            f"Pixel {pid} mismatch: rain_pixels says {row['n_cells']}, cells say {expected_count}"
        )

def test_crs_round_trip(cells_df):
    """UTM 43N (EPSG:32643) to WGS84 (EPSG:4326) and back must preserve coordinates within 1.0 m."""
    trans_fwd = Transformer.from_crs("EPSG:32643", "EPSG:4326", always_xy=True)
    trans_rev = Transformer.from_crs("EPSG:4326", "EPSG:32643", always_xy=True)

    sample = cells_df.sample(n=min(200, len(cells_df)), random_state=42)
    lons, lats = trans_fwd.transform(sample["x_utm"].values, sample["y_utm"].values)
    x_back, y_back = trans_rev.transform(lons, lats)

    dist_diff = np.sqrt((sample["x_utm"].values - x_back)**2 + (sample["y_utm"].values - y_back)**2)
    assert (dist_diff < 1.0).all(), f"CRS round-trip maximum drift {dist_diff.max():.4f} m exceeds 1.0 m limit"

def test_topological_neighbour_count_bounds(cells_df):
    """Every cell must have <= 8 neighbours in 3x3 lattice; unclipped interior cells must have exactly 8."""
    min_x = cells_df["lattice_center_x"].min() - 250
    min_y = cells_df["lattice_center_y"].min() - 250
    spacing = 500.0

    cols = ((cells_df["lattice_center_x"] - 250 - min_x) / spacing).round().astype(int)
    rows = ((cells_df["lattice_center_y"] - 250 - min_y) / spacing).round().astype(int)

    cell_positions = set(zip(cols, rows))
    valid_ids = set(cells_df["cell_id"])

    # Map each position to cell_id
    pos_to_id = {(c, r): cid for (c, r), cid in zip(zip(cols, rows), cells_df["cell_id"])}

    for (c, r), cid in pos_to_id.items():
        nbr_ids = []
        for dc in [-1, 0, 1]:
            for dr in [-1, 0, 1]:
                if dc == 0 and dr == 0:
                    continue
                pos = (c + dc, r + dr)
                if pos in pos_to_id:
                    nbr_ids.append(pos_to_id[pos])

        assert len(nbr_ids) <= 8, f"Cell {cid} has {len(nbr_ids)} > 8 neighbours"
        assert set(nbr_ids).issubset(valid_ids), f"Cell {cid} has out-of-grid neighbour IDs"

def test_census_2011_area_check(cells_df):
    """Total cell area sum (711.59 km²) must be within 1.0% of official Census 2011 area (709.49 km²)."""
    census_area = 709.49
    total_area = cells_df["area_km2"].sum()
    pct_diff = abs(total_area - census_area) / census_area * 100.0
    assert pct_diff <= 1.0, f"Total grid area {total_area:.2f} km² differs by {pct_diff:.2f}% (> 1.0%) from Census 2011 ({census_area} km²)"

def test_grid_determinism():
    """Running 01_grid.py again must produce identical CSV output."""
    with open(CELLS_CSV, "rb") as f:
        original_bytes = f.read()

    res = subprocess.run([".venv/bin/python", "pipeline/01_grid.py"], capture_output=True, text=True)
    assert res.returncode == 0, f"01_grid.py failed on rerun: {res.stderr}"

    with open(CELLS_CSV, "rb") as f:
        rerun_bytes = f.read()

    assert original_bytes == rerun_bytes, "Grid generation is non-deterministic!"
