"""pipeline/05_report.py
Generates reports/stage1_summary.md directly from pipeline CSV outputs and git metadata.
Follows Stage 1 reporting rules:
- Positive cell-days reported as SEED cells x event days only.
- 3x3 neighbour count kept purely as an audit buffer flag, retired as a yield.
- Reports seed-only volume plainly against the spec targets (100 min / 500 target).
- Kept concise to one page.

Usage:
    python pipeline/05_report.py
"""

import os
import hashlib
import subprocess
import pandas as pd

def compute_sha256(filepath):
    if not os.path.exists(filepath):
        return "MISSING"
    with open(filepath, "rb") as f:
        return hashlib.sha256(f.read()).hexdigest()

def get_git_commit():
    try:
        res = subprocess.run(["git", "rev-parse", "HEAD"], capture_output=True, text=True, check=True)
        return res.stdout.strip()
    except Exception:
        return "UNKNOWN"

def generate_summary():
    cells_csv = "data/interim/cells_grid.csv"
    rain_pixels_csv = "data/interim/rain_pixels.csv"
    events_with_cells_csv = "data/interim/events_with_cells.csv"
    raw_events_csv = "data/events.csv"
    event_cells_csv = "data/interim/event_cells.csv"
    out_md = "reports/stage1_summary.md"

    commit_hash = get_git_commit()
    events_hash = compute_sha256(raw_events_csv)
    cells_hash = compute_sha256(cells_csv)

    cells = pd.read_csv(cells_csv)
    pixels = pd.read_csv(rain_pixels_csv)
    events = pd.read_csv(events_with_cells_csv)
    event_cells = pd.read_csv(event_cells_csv) if os.path.exists(event_cells_csv) else pd.DataFrame()

    n_cells = len(cells)
    full_cells = (cells["area_km2"] >= 0.2499).sum()
    clipped_cells = (cells["area_km2"] < 0.2499).sum()
    total_area = cells["area_km2"].sum()
    n_wards = cells["ward"].nunique()
    n_pixels = len(pixels)

    # Seed-only positive cell-days calculation
    durations = {
        'E2022_09': 3,
        'E2022_05': 1,
        'E2021_11': 1,
        'E2017_08': 1,
        'E2017_09': 2,
        'E2023_05': 1
    }

    seeds_df = event_cells[event_cells["role"] == "seed"] if not event_cells.empty else pd.DataFrame()
    per_event_seeds = {}
    tot_seed_days = 0

    for eid, days in durations.items():
        if not seeds_df.empty:
            distinct_seeds = sorted(list(set(seeds_df[seeds_df["event_id"] == eid]["cell_id"])))
        else:
            distinct_seeds = []
        seed_days = len(distinct_seeds) * days
        tot_seed_days += seed_days
        per_event_seeds[eid] = (distinct_seeds, len(distinct_seeds), seed_days)

    # 3x3 neighbours buffer count (audit flag only)
    nbr_cells_total = event_cells[event_cells["role"] == "neighbour_3x3"]["cell_id"].nunique() if not event_cells.empty else 0

    content = f"""# Stage 1 Summary Report: Spatial Skeleton and Event Linkage

**Generated by**: `pipeline/05_report.py`  
**Git Commit**: `{commit_hash}`  
**Events SHA-256 (`data/events.csv`)**: `{events_hash}`  
**Cells Grid SHA-256 (`data/interim/cells_grid.csv`)**: `{cells_hash}`  

---

## 1. Grid Specifications (500 m Full-City Bengaluru)

- **Total Grid Cells**: {n_cells:,} ({full_cells:,} full 0.25 km² cells, {clipped_cells:,} clipped boundary cells)
- **Total Mapped Area**: {total_area:.2f} km² across {n_wards}/198 wards (BBMP 2011 delimitation)
- **CHIRPS Native Rain Pixels**: {n_pixels} pixels (0.05° resolution; mean {pixels['n_cells'].mean():.1f} cells/pixel)
- **Total Event Rows**: {len(events)} rows across {events['event_id'].nunique()} events (all {len(events)} strictly inside production grid)

---

## 2. Seed-Only Positive Cell-Days Yield vs. Spec Targets

*Rule: Positive labels are strictly SEED cells × event days. Topological 3x3 neighbours are retired as a yield and retained solely as an audit flag.*

| Event ID | Dates | Window | Seed Cell IDs | Unique Seeds/Day | Seed-Days |
|---|---|:---:|---|:---:|:---:|
| `E2022_09` | 2022-09-05 to 2022-09-07 | 3 days | {per_event_seeds['E2022_09'][0]} | {per_event_seeds['E2022_09'][1]} | **{per_event_seeds['E2022_09'][2]}** |
| `E2022_05` | 2022-05-05 | 1 day | {per_event_seeds['E2022_05'][0]} | {per_event_seeds['E2022_05'][1]} | **{per_event_seeds['E2022_05'][2]}** |
| `E2021_11` | 2021-11-21 | 1 day | {per_event_seeds['E2021_11'][0]} | {per_event_seeds['E2021_11'][1]} | **{per_event_seeds['E2021_11'][2]}** |
| `E2017_08` | 2017-08-15 | 1 day | {per_event_seeds['E2017_08'][0]} | {per_event_seeds['E2017_08'][1]} | **{per_event_seeds['E2017_08'][2]}** |
| `E2017_09` | 2017-09-27 to 2017-09-28 | 2 days | {per_event_seeds['E2017_09'][0]} | {per_event_seeds['E2017_09'][1]} | **{per_event_seeds['E2017_09'][2]}** |
| `E2023_05` | 2023-05-21 | 1 day | {per_event_seeds['E2023_05'][0]} | {per_event_seeds['E2023_05'][1]} | **{per_event_seeds['E2023_05'][2]}** |
| **Total** | | | | | **{tot_seed_days} seed-days** |

### Spec Target Comparison (Section 4.2)
- **Minimum Spec Target (100 positive cell-days)**: **{tot_seed_days} / 100 ({tot_seed_days/100:.1%})** — Current verified seeds provide {tot_seed_days/100:.1%} of minimum volume.
- **Good Spec Target (500 positive cell-days)**: **{tot_seed_days} / 500 ({tot_seed_days/500:.1%})** — Additional verified candidate events required to meet target.
- **Audit Flag (3x3 Topological Buffer)**: Encompasses {nbr_cells_total} unique adjacent cells across events (used strictly for spatial sanity checks; never counted as positives).

---

## 3. Ground Truth Verification Summary (`data/events.csv`)
*(Note: Ward assignments reflect spatial polygon joins from the BBMP 2011 boundary; they repeat our GIS join and are not independently verified).*

| Event ID | Location Name | Primary Seed | Ward | Confidence | Audit Note |
|---|---|:---:|---|:---:|---|
| `E2022_09` | RBD Layout (Sarjapur Road) | Cell 555 | Ward 150 | High | Moved to inside centroid (555); CFG_C footprint seeds: [554, 555, 608] |
| `E2022_09` | Wipro Campus (Sarjapur Road) | Cell 666 | Ward 150 | High | Moved to campus centroid (666); CFG_C footprint seeds: [665, 666] |
| `E2022_09` | Outer Ring Road (RMZ Ecospace) | Cell 847 | Ward 150 | High | Kept stored coordinate; strictly inside Cell 847 |
| `E2022_09` | Epsilon Layout / Yemalur Road | Cell 910 | Ward 150 | High | Kept stored coordinate; strictly inside Cell 910 |
| `E2022_09` | Borewell Road (Whitefield) | Cell 1444 | Ward 84 | High | Kept stored coordinate; strictly inside Cell 1444 |
| `E2022_09` | Panathur-Balagere Road | Cell 977 | Ward 150 | High | Kept stored coordinate; strictly inside Cell 977 |
| `E2022_05` | RBD Layout (Sarjapur Road) | Cell 555 | Ward 150 | Medium | Pre-monsoon storm; footprint seeds: [554, 555, 608] |
| `E2021_11` | Yelahanka / Jakkur (Kendriya Vihar) | Cell 2882 | Ward 1 | Low | Kept stored point (2882); condition (ii) origin unexplained; move to 2904 proposed |
| `E2017_08` | Koramangala 4th Block | Cell 897 | Ward 151 | Medium | Moved to OSM polygon centroid (897); behind 80 Feet Rd (TNM 2017-10-04) |
| `E2017_09` | Hosur-Sarjapur / Anugraha | Cell 774 | Ward 173 | Medium | Kept stored coordinate; citation URL unverified (redirected); proposal: low |
| `E2023_05` | KR Circle Underpass | Cell 1478 | Ward 110 | Medium | Flooded underpass fatality (21 May 2023); junction way 1096077212 proxy |

---

## 4. Key Artifacts Produced

1. `data/events.csv`: Primary event register with primary seed `cell_id` and audit columns.
2. `data/interim/event_cells.csv`: 101 rows mapping `(event_id, place, cell_id, role)` for seeds and 3x3 neighbours.
3. `data/interim/source_check_log.csv`: Audit log of all fetched citation URLs with HTTP status and verdicts.
4. `data/interim/events_with_cells.csv`: Point-in-polygon verification and cell edge distance metrics.
"""

    os.makedirs(os.path.dirname(out_md), exist_ok=True)
    with open(out_md, "w") as f:
        f.write(content)
    print(f"Report successfully generated at {out_md}")

if __name__ == "__main__":
    generate_summary()
